fitbox/base/urls.py
from django.urls import path

from fitbox.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

fitbox/cadastro_paciente/urls.py
from django.urls import path

from fitbox.cadastro_paciente.views import cadastro_paciente, indice, detalhe_paciente, PacientCreateView

app_name = 'cadastro'
urlpatterns = [
    path('', cadastro_paciente, name='cadastro_paciente'),
    path('popup/', PacientCreateView.as_view(), name='cadastro_paciente_popup'),
    path('pacientes/', indice, name='indice'),
    path('pacientes/<slug:slug>/', detalhe_paciente, name='dados_paciente'),
]

fitbox/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitbox.base.urls')),
    path('cadastro_paciente/', include('fitbox.cadastro_paciente.urls')),
    path('consulta/', include('fitbox.consultas.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

fitbox/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migration = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password
        :param email:
        :param password:
        :param extra_fields:
        :return:
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_staff", True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base user class
    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = str(self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

fitbox/base/views.py
from django.shortcuts import render
# Create your views here.


def home(request):
    return render(request, 'base/home.html')

fitbox/base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Minha dieta{% endblock %}</title>
	<meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{% static 'images/lab-exames.png' %}" >
    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">
    <link href="{% static 'css/form.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>

</head>

<body>

    {% block body %}{% endblock %}


	<footer id="rodape">
		<p>Copyright © {% now 'Y' %} - by Abraão Vila Nova e Lucas Ravellys</p>
	</footer>


</body>
</html>

fitbox/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}FitBox{% endblock title %}
<!--- Código Lucas
{% block body %}
	<div id="interface">
			<img id="img-logo" src="{% static 'images/logo-index.png' %}" alt="FitBox"/>
			<div id="meus-pacientes">
				<a href="{% url 'cadastro:indice' %}">
					<p><img class="img-paciente" src="{% static 'images/pacientes.png' %}"/><p>
					<p>Meus Pacientes</p>
				</a>
			</div>
			<div id="novo-paciente" class="col-md-9" >

                <div class=" modal fade" tabindex="-1" role="dialog" id="modal">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content"></div>
                  </div>
                </div>
                <button id="novo-cadastro" class="btn btn-outline-dark" type="button" name="button">

                 <div class="row-cols-md-2 pr-4 d-sm-flex">
                    <div class="col-md-4">
                        <p>Adicionar Paciente</p>
                    </div>
                    <div class="col-md-4 h-25 w-25 ">
				        <img class="card-img-top" src="{% static 'images/novo-paciente.png' %}"/>
                    </div>
                 </div>

                </button>
			</div>
    </div>

    <script type="text/javascript">
    $(document).ready(function() {

    $("#novo-cadastro").modalForm({
        formURL: "{% url 'cadastro:cadastro_paciente_popup' %}"
    });

    });
    </script>


{% endblock %}
  -->
{% block body %}
<div class="container bg-light shadow-sm">
  <div class="row mt-1">
      <div class="col-12 mt-3 text-center">
          <img src="{% static 'images/logo-index.png' %}" width="92"  alt="logo">
          <h1 class="h3 text-secondary">FitBox</h1>
          <p class="text-secondary">Saúde e Tecnologia</p>
      </div>
  </div>

  
  <div class="mt-md-3 d-flex justify-content-center">
      <div class="p-2 flex bd-highlight">
          <a class="text-secondary lh-2 btn btn-light" href="{% url 'cadastro:indice' %}">
              <div class="text-center">
                  <span>
                      <img src="{% static 'images/pacientes.png' %} class="mx-auto d-block" alt="" width="72">
                  </span>
                  <span>
                      Meus<br>Pacientes
                  </span>
              </div>
          </a>
          <a class="text-secondary lh-2 btn btn-light" id="novo-cadastro" href="{% static 'images/novo-paciente.png' %}">
              <div>
                  <span>
                      <img src="{% static 'images/novo-paciente.png' %}" class="mx-auto d-block"alt="" width="72">

                  </span>
                  <span>
                      Novos <br>Pacientes
                  </span>

              </div>
          </a>
      </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function() {

  $("#novo-cadastro").modalForm({
      formURL: "{% url 'cadastro:cadastro_paciente_popup' %}"
  });

  });
  </script>


{% endblock %}