fitbox/cadastro_paciente/urls.py
from django.urls import path

from fitbox.cadastro_paciente.views import cadastro_paciente, indice, detalhe_paciente, PacientCreateView

app_name = 'cadastro'
urlpatterns = [
    path('', cadastro_paciente, name='cadastro_paciente'),
    path('popup/', PacientCreateView.as_view(), name='cadastro_paciente_popup'),
    path('pacientes/', indice, name='indice'),
    path('pacientes/<slug:slug>/', detalhe_paciente, name='dados_paciente'),
]

fitbox/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitbox.base.urls')),
    path('cadastro_paciente/', include('fitbox.cadastro_paciente.urls')),
    path('consulta/', include('fitbox.consultas.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

fitbox/cadastro_paciente/models.py
from django.db import models


# Create your models here.
from django.template.defaultfilters import slugify
from django.urls import reverse


class CadastroPaciente(models.Model):
    SEXO_CHOICES = [
        ["F", "Feminino"],
        ["M", "Masculino"]
    ]

    nome = models.CharField(max_length=32)
    nascimento = models.DateField()
    email = models.EmailField(unique=True)
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES, null=True)
    creation = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=32)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nome)
        super(CadastroPaciente, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('cadastro:dados_paciente', args=(self.slug, ))

    def __str__(self):
        return self.nome

fitbox/cadastro_paciente/forms.py
# from django import forms

from fitbox.cadastro_paciente.models import CadastroPaciente
from bootstrap_modal_forms.forms import BSModalModelForm


class CadastroPacienteForm(BSModalModelForm):
    class Meta:
        model = CadastroPaciente
        fields = ['nome', 'email', 'nascimento', 'sexo']

fitbox/cadastro_paciente/views.py
from bootstrap_modal_forms.generic import BSModalCreateView
from django.shortcuts import render, redirect
# from django.views.generic import ListView
from django.urls import reverse_lazy

from fitbox.cadastro_paciente import facade
from fitbox.cadastro_paciente.forms import CadastroPacienteForm
from fitbox.cadastro_paciente.models import CadastroPaciente


def cadastro_paciente(request):
    form = CadastroPacienteForm()
    if request.method == 'POST':
        form = CadastroPacienteForm(request.POST)
        if form.is_valid():
            print('saving')
            form.save(commit=True)
            return redirect('/cadastro_paciente')
        else:
            print("error")

    return render(request, 'cadastro_paciente/cadastro_paciente.html', context={"form": form})


class PacientCreateView(BSModalCreateView):
    template_name = 'cadastro_paciente/cadastro_paciente_popup.html'
    form_class = CadastroPacienteForm
    success_message = 'Success: pacint was created.'
    success_url = reverse_lazy('base:home')


def indice(request):
    pacientes = CadastroPaciente.objects.order_by('nome').all()
    return render(request, 'cadastro_paciente/paciente.html',
                  context={"pacientes": pacientes})


def detalhe_paciente(request, slug):
    paciente = facade.encontrar_paciente(slug)
    return render(request, 'cadastro_paciente/dados_paciente.html', {'paciente': paciente})

fitbox/cadastro_paciente/templates/cadastro_paciente/cadastro_paciente.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}FitBox - Cadastro{% endblock title %}

{% block body %}
    <div id="interface">
      <form onsubmit="{% url 'cadastro:cadastro_paciente' %}" method="post">
        {% csrf_token %}

         <table>
         <tr>
             <td>
                 <tr>
                     <td>Nome Completo:</td>
                     <td>{{ form.nome }}</td>
                 </tr>
                 <tr>
                     <td>Email</td>
                     <td>{{ form.email }}</td>
                 </tr>
                 <tr>
                     <td>Data de nascimento</td>
                     <td>{{ form.nascimento }}</td>
                 </tr>
                 <tr>
                     <td>Sexo</td>
                     <td>{{ form.sexo }}</td>
                 </tr>
             </td>
             <td>
                 <input type="submit" id="name" class="btn btn-dark" value="Enviar" />
             </td>
         </tr>

        </table>
      </form>


    </div>


{% endblock %}

fitbox/cadastro_paciente/templates/cadastro_paciente/cadastro_paciente_popup.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}FitBox - Cadastro{% endblock title %}

{% block body %}

        <form method="post" action="">
          {% csrf_token %}

         <div class="modal-header">
            <h5 class="modal-title">Novo Paciente</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            {% for field in form %}
              <div class="form-group{% if field.errors %} invalid{% endif %}">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% for error in field.errors %}
                  <p class="help-block">{{ error }}</p>
                {% endfor %}
              </div>
            {% endfor %}
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="submit-btn btn btn-primary">Create</button>
          </div>

        </form>


{% endblock %}

fitbox/cadastro_paciente/templates/cadastro_paciente/dados_paciente.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}FitBox - Cadastro{% endblock title %}

{% block body %}
    <div id="interface">

       <table>
         <tr>
             <td>
                 <tr>
                     <td>Nome Completo:</td>
                     <td>{{ paciente.nome }}</td>
                 </tr>
                 <tr>
                     <td>Email</td>
                     <td>{{ paciente.email }}</td>
                 </tr>
                 <tr>
                     <td>Data de nascimento</td>
                     <td>{{ paciente.nascimento }}</td>
                 </tr>
                 <tr>
                     <td>Sexo</td>
                     <td>{{ paciente.sexo }}</td>
                 </tr>
             </td>
         </tr>

        </table>


    </div>


{% endblock %}

fitbox/cadastro_paciente/templates/cadastro_paciente/paciente.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}FitBox - Pacientes{% endblock title %}

{% block body %}

            <div id="interface">

                <table>
                    <thead><h1>Lista de Pacientes</h1></thead>
                <tbody>
                    {% for paciente in pacientes %}
                    <tr>
                        <a href="{{ paciente.get_absolute_url }}">{{ paciente.nome | default:'Faltando Título' }}</a>
                    </tr>
                    </tbody>
                </table>
                    {% empty %}
                        Sem Pacientes
                    {% endfor %}

            </div>

{% endblock %}